# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171215_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='intro',
        ),
    ]
